import type { DemoScenario, DemoScenarioId } from "./types";

export const DEMO_SCENARIOS: Record<DemoScenarioId, DemoScenario> = {
  routine: {
    id: "routine",
    index: "01",
    label: "Routine booking",
    title: "No cooling after hours",
    prompt: "Pretend your AC stopped cooling at 10:47 PM.",
    test: "Qualification, service-area validation, and provisional booking.",
    duration: "~82 sec",
    transcript: [
      { speaker: "fieldrelay", atSeconds: 0, text: "Thanks for calling FieldRelay's service-line demo. This is an AI-assisted demonstration. May I continue?" },
      { speaker: "caller", atSeconds: 8, text: "Yes. My air conditioner is running, but the house is not cooling." },
      { speaker: "fieldrelay", atSeconds: 16, text: "I can help capture this for dispatch. Is anyone in immediate danger, or do you smell smoke or gas?" },
      { speaker: "caller", atSeconds: 25, text: "No. It is uncomfortable, but safe." },
      { speaker: "fieldrelay", atSeconds: 31, text: "Understood. May I have your name, service ZIP, and street address?" },
      { speaker: "caller", atSeconds: 39, text: "Jordan Lee, 78704, 814 South First Street." },
      { speaker: "system", atSeconds: 47, text: "Service area validated · Routine cooling request · No emergency signals" },
      { speaker: "fieldrelay", atSeconds: 53, text: "Your address is in range. I can hold tomorrow's 9 to 11 AM arrival window for dispatcher confirmation. Does that work?" },
      { speaker: "caller", atSeconds: 64, text: "Yes, that works." },
      { speaker: "system", atSeconds: 71, text: "Provisional booking created · Dispatcher receipt prepared" },
    ],
    receipt: {
      decision: "book",
      outcome: "Provisional booking captured",
      callerName: "Jordan Lee",
      service: "Residential AC not cooling",
      location: "Austin, TX 78704",
      serviceArea: "inside",
      urgency: "routine",
      appointment: "Tomorrow, 9-11 AM, pending dispatcher confirmation",
      handoff: null,
      safeguards: ["Danger screen completed", "No diagnosis offered", "Arrival window marked provisional"],
      dispatcherSummary: "Safe, in-area no-cooling request. Unit runs but does not cool. Customer accepted tomorrow 9-11 AM pending dispatcher confirmation.",
    },
  },
  emergency: {
    id: "emergency",
    index: "02",
    label: "Emergency handoff",
    title: "Active water leak",
    prompt: "Report water spreading near an electrical panel.",
    test: "Danger recognition, intake restraint, and human escalation.",
    duration: "~54 sec",
    transcript: [
      { speaker: "fieldrelay", atSeconds: 0, text: "Thanks for calling FieldRelay's service-line demo. This is an AI-assisted demonstration. May I continue?" },
      { speaker: "caller", atSeconds: 7, text: "Yes. Water is coming through the ceiling near our electrical panel." },
      { speaker: "fieldrelay", atSeconds: 15, text: "I will not troubleshoot that by phone. Please keep away from the affected area. If anyone is in immediate danger, contact emergency services now." },
      { speaker: "system", atSeconds: 25, text: "Emergency language detected · Routine intake stopped" },
      { speaker: "fieldrelay", atSeconds: 31, text: "I am marking this urgent and routing the call to the on-call person with your summary." },
      { speaker: "caller", atSeconds: 41, text: "Okay. Please connect me." },
      { speaker: "system", atSeconds: 46, text: "Human escalation requested · Context package attached" },
    ],
    receipt: {
      decision: "escalate",
      outcome: "Emergency handoff triggered",
      callerName: "Caller not yet identified",
      service: "Active water leak near electrical equipment",
      location: "Unconfirmed",
      serviceArea: "unconfirmed",
      urgency: "emergency",
      appointment: null,
      handoff: "On-call human · Immediate",
      safeguards: ["Troubleshooting prohibited", "Emergency-services language delivered", "Routine intake stopped"],
      dispatcherSummary: "Caller reports active water intrusion near electrical panel. No diagnosis attempted. Immediate human escalation requested before routine qualification.",
    },
  },
  boundary: {
    id: "boundary",
    index: "03",
    label: "Policy boundary",
    title: "Price request outside area",
    prompt: "Ask for a firm water-heater quote from an unsupported ZIP.",
    test: "Service-area boundary, estimate refusal, and clean capture.",
    duration: "~67 sec",
    transcript: [
      { speaker: "fieldrelay", atSeconds: 0, text: "Thanks for calling FieldRelay's service-line demo. This is an AI-assisted demonstration. May I continue?" },
      { speaker: "caller", atSeconds: 7, text: "Yes. I need a firm quote for a new water heater. I am in ZIP 78666." },
      { speaker: "fieldrelay", atSeconds: 16, text: "I cannot provide estimates or confirm service before checking your location. Let me validate that ZIP." },
      { speaker: "system", atSeconds: 26, text: "ZIP outside configured service area · Estimate tool blocked" },
      { speaker: "fieldrelay", atSeconds: 33, text: "That ZIP is outside this demo contractor's current service area. I can capture your request for manual review, but I cannot promise service or pricing." },
      { speaker: "caller", atSeconds: 47, text: "Please have someone confirm." },
      { speaker: "fieldrelay", atSeconds: 53, text: "I will send a review request. No appointment or price is confirmed." },
      { speaker: "system", atSeconds: 60, text: "Manual review captured · No booking created" },
    ],
    receipt: {
      decision: "capture",
      outcome: "Manual review captured",
      callerName: "Caller not yet identified",
      service: "Water-heater replacement quote request",
      location: "San Marcos, TX 78666",
      serviceArea: "outside",
      urgency: "routine",
      appointment: null,
      handoff: "Dispatcher review · No service promise",
      safeguards: ["Firm estimate prohibited", "Unsupported ZIP disclosed", "No appointment promised"],
      dispatcherSummary: "Out-of-area caller requests firm water-heater replacement quote. System declined pricing and service promise, then captured manual review request.",
    },
  },
};

export function getDemoScenario(id: DemoScenarioId) {
  return DEMO_SCENARIOS[id];
}
